### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by belisards** [grama-cc/nuvela#5]
Alguns vídeos não estão dando autoplay automaticamente. Aparece o botão do PLAY, mas ao clicar só MUTA ou não o vídeo.

Não consegui identificar nada de anormal, nem a razão pela qual isso acontece. Aparentemente tá tudo igual na planilha.

Se acontecer alguma coisa, alguma sugestão de como debugar?

**Comment by sulram** [comment]
@belisards na verdade acho que isso ocorre nos vídeos onde o `end` coincide com o final do vídeo. percebi também que as vezes o vídeo termina um pouco antes do `end` informado na planilha.

**Comment by belisards** [comment]
mas se fosse isso ele teria que "congelar" no final, não no início do vídeo
- ou não?


2016-03-23 12:20 GMT-03:00 Marlus Araujo <notifications@github.com>:

> @belisards <https://github.com/belisards> na verdade acho que isso ocorre
> nos vídeos onde o end coincide com o final do vídeo. percebi também que
> as vezes o vídeo termina um pouco antes do end informado na planilha.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/grama-cc/nuvela/issues/5#issuecomment-200390983>
>



-- 
•adrianobf@gmail.com•

**Comment by sulram** [comment]
então, acho que ele está congelando no final, aí aparece o botão de replay

**Comment by euharrison** [comment]
É, parece um bug mesmo, vamos investigar com atenção.

Se acontecer de novo, por favor cliquem com o botão direito do mouse, escolham `inspect` e depois a aba `network` e mandem um print

**Comment by edinhoo** [comment]
Corrigi o bug, agora ele chama o próximo vídeo quando o atual acaba :)

**Comment by sulram** [comment]
@edinhoo hoje eu reparei que um video que estava indo ate o final e parava com o botao de play. voce atualizou la no servidor? ou sera que o erro continua?

**Comment by edinhoo** [comment]
@sulram corrigi o bug do vídeo que travava e não chamava o próximo. Mas eu não entendi o que aconteceu hoje, o video era para terminar antes do final e passar para o próximo mas não passou e quando chegou no fim deu stop e parou tudo?

**Comment by sulram** [comment]
sim, foi isso que aconteceu. ele parou com a imagem de capa do vídeo e um botão de play, como se tivesse loopado, mas sem opção de autoplay

**Comment by edinhoo** [comment]
@belisards sabe em qual vídeo foi? me passa o id que eu dou uma olhada :)

**Comment by sulram** [comment]
foi esse aqui, que é bem o trecho final
https://www.youtube.com/watch?v=_-G86ZT7Daw

**Comment by sulram** [comment]
acho que resolveu né? vou fechar aqui
