### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by belisards** [grama-cc/nuvela#6]
Oi, algumas sugestões de interface:

- Incluir um ícone no upac.com.br pra Nuvela no menu da direita
- Ideia: colocar a logo da NUVELA no clip com a estática que aparece entre os vídeos. No lugar dela, inserir logo da UPAC com link pro upac.com.br
- Inserir um link discreto pro github em algum lugar? De modo discreto no rodapé direito da aba que abre ao clicar no +, de repente?

Coloco aqui pra registrar as ideias e pra saber o que acham ...

**Comment by sulram** [comment]
legal @belisards 

vamos trabalhando nisso até o lançamento dia 8/4

vou adicionar o icone da nuvela no site da upac

seria uma boa fazer um texto sobre o conceito da NUVELA pra colocar no README, como o repositório da UPAC: https://github.com/ultraleve/upac

o link para o github pode ser a info de creative commons + créditos (sugestões? @euharrison @edinhoo )

`(cc) 2016 NUVELA – UPAC.` [`Créditos, licença e código aberto`](https://github.com/grama-cc/nuvela/)

estava falando com @chcl e @anastacio para ajudar a pensar o gif glitch da estática

**Comment by euharrison** [comment]
@sulram acho que vc pode ajudar mais nessa, vou enumerar os itens para facilitar a conversa

1 - **link no site upac.com.br**: Acho muito importante, vc já tem um forma de fazer isso? Quer q a gente assuma isso? Precisaríamos remontar o setup do projeto da upac

2 - ** estática**: @edinhoo propôs a estática mas o que rola por trás é só um gif animado. Então podemos remontar esse gif a vontade. @sulram vc é familiarizado com isso? Qualquer coisa podemos pedir uma ajuda ao pessoal da Relâmpago, eles costumam trabalhar legal com gifs animados

3 - **link github**: super a favor! No site da Grama será algo como `< />`, será discreto e funcional

**Comment by euharrison** [comment]
ops, postei junto

@sulram acho muito legal usar o que vc propôs como link do github, vou seguir com ela, blz?

**Comment by sulram** [comment]
@euharrison @edinhoo depois eu queria fazer umas alterações no design, mudar o tamanho e aparência do gradiente. em breve vou enviar um arquivo detalhando isso.

Os vídeos sempre ficam com aquela borda preta. Será que podemos criar um modo "cover", pra ele expandir e sempre ocupar toda a janela? Talvez só tenha como fazer colocando posição absoluta e verificando a proporção e resolução de cada vídeo. A marca da NUVELA ficaria melhor posicionada, com as barras pretas sempre parece que ela está na posição errada.

**Comment by euharrison** [comment]
@sulram vamos trabalhar no modo cover e seguir um padrão de que todos os vídeos são 16:9 e também ajustar o gradiente
