### ISSUE TITLE
Sobre a NUVELA

### ISSUE THREAD

**Issue by sulram** [grama-cc/nuvela#7]
atualizei o `README` @belisards
https://github.com/grama-cc/nuvela

**Comment by sulram** [comment]
@euharrison @edinhoo

podem colocar o @belisards no projeto para ele editar o README?

abs!

**Comment by euharrison** [comment]
@sulram, adicionei o @belisards

aproveitei para te deixar como admin também, assim vc também pode fazer isso no futuro caso precise :)

**Comment by sulram** [comment]
valeu @euharrison ! @belisards, pode trabalhar no README

**Comment by euharrison** [comment]
Vou fechar essa issue, acredito q ela já esteja pronta. Qualquer coisa podemos abrir uma nova para o README versão 2.0
